# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet build
  test: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test
  # analyze: 
  # package: 
  # deploy: 

name: cibuild

on: push

# if we don't care about branches, we can just use on: push
# if we care about the branch:
# on:
#   push:
#     branches:
#       - master

# person:
#   firstName: 'string' # string
#   lastName: 100 # number
#   middleName: true # boolean
#   alias:  # collection
#     - 'dotnet'  # dash indicates part of a collection
#     - 'lead'
#     - subAlias:
    